ParkingLot 삭제 추가, 멤버 수정시 저장값 반환하도록 변경
f-lab-edu/par-king pull request #11
Opened 2024-03-18 18:25 UTC by acecic82

주차장 삭제 추가

1. deleted_at column 을 추가하여 삭제 시 삭제 시점으로 update 되도록 변경
2. 처음 ParkingLot이 생성될 때 이 column 은 1970년 1월 1일 이전의 랜덤값으로 저장되도록 추가(랜덤 5년 범위내)

멤버 저장시 저장 값 반환하도록 변경

1.수정, 저장

2024-03-19 23:02 UTC, f-lab-scott requested changes
수고하셨습니다. 몇 가지 의견 남겨요.

2024-03-19 23:02 UTC, f-lab-scott commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotInquiryController.kt
> +        @RequestParam memberId: String
내가 등록한 것인데, 보안 체크는 들어가지 않네요?
로그인한 사용자 자신의 것만 봐야 하지 않을까요? `@AuthenticationPrincipal ` 같은거 사용하면 좋을 텐데요.

2024-03-19 23:02 UTC, f-lab-scott commented on api/src/main/kotlin/com/parking/api/adapter/out/ParkingLotInquiryAdapter.kt
> +class ParkingLotInquiryAdapter(
자신의 정보를 가져오는 스펙이 표현돼야 할 것 같습니다.

2024-03-19 23:02 UTC, f-lab-scott commented on domain/src/main/kotlin/com/parking/domain/entity/ParkingLot.kt
> +        //5년 범위 안에 랜덤 값
지금 요거는 domain보단 DB persist에만 필요한 값이므로 JPA Entity에만 위치해도 된다고 생각합니다.

2024-03-20 02:56 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotCommandController.kt
> +    private val deleteParkingLot: DeleteParkingLotUseCase
그렇네요 수정하겠습니다

2024-03-20 02:57 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotCommandController.kt
> +        @RequestParam parkingLotId: Long
아~ 그렇군요 변경하겠습니다

2024-03-20 02:58 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotInquiryController.kt
> +        @RequestParam memberId: String
확인해보겠습니다

2024-03-20 03:00 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/out/ParkingLotInquiryAdapter.kt
> +class ParkingLotInquiryAdapter(
이 부분은 어떤 말씀인지 잘 이해가 안갑니다. "ParkingLotInquiryAdapter" 이 이름은 단순히 ParkingLot의 read 관련된 부분 adapter 라서요 자신의 정보를 가져온다는게 무슨 말씀인지 모르겠습니다 @f-lab-scott

2024-03-20 03:02 UTC, acecic82 commented on domain/src/main/kotlin/com/parking/domain/entity/ParkingLot.kt
> +        //5년 범위 안에 랜덤 값
그렇네요 하지만 이건 비지니스 로직의 일부라고 생각해서 도메인에 위치시켰는데 많이 어색할까요? @f-lab-scott

2024-03-20 03:42 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotCommandController.kt
> +    private val deleteParkingLot: DeleteParkingLotUseCase
수정완료

2024-03-20 03:42 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotCommandController.kt
> +        @RequestParam parkingLotId: Long
수정 완료

2024-03-20 05:54 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotCommandController.kt
> +    @DeleteMapping("/delete")
수정하겠습니다~

2024-03-20 05:55 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotCommandController.kt
> +    @DeleteMapping("/delete")
수정 완료

2024-03-20 06:06 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotCommandController.kt
> +    @DeleteMapping("/delete")
이거 좀 더 찾아봤는데 202의 의미가 받아들여졌다. 즉 비동기적 관점에서 사용한다고 하더라구요. 처리가 오래 걸리는 경우 해당 요청이 제대로 들어온것은 맞다? 정도로 해석되는데 이건 delete를 완료 후 제대로 됐으면 return이 갈거라 기존처럼 200이 더 맞지 않을지 여쭤봅니다. @f-lab-scott  

202 Accepted on the other hand means that the request have been accepted for processing, and the service will now start. This does not mean that the processing itself is a success, nor that the process have ended.

2024-03-20 12:11 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotInquiryController.kt
> +        @RequestParam memberId: String
수정하겠습니다

2024-03-20 12:24 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotInquiryController.kt
> +        @RequestParam memberId: String
수정 완료

2024-03-20 15:17 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotInquiryController.kt
> +        @RequestParam memberId: String
AOP로 만들어보려다가 만드려면 MemberId가 필수 파라미터라 적합하지 않다고 해서 접었습니다

2024-03-20 23:14 UTC, f-lab-scott commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotCommandController.kt
> +    @DeleteMapping("/delete")
아 그렇긴 한데 보통 관용적으로 이런경우에도 202를 쓰긴 합니다

2024-03-20 23:14 UTC, f-lab-scott commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotCommandController.kt
> +    @DeleteMapping("/delete")
요건 판단하셔서 200을 내리셔도 될거같네요 그럼

2024-03-20 23:15 UTC, f-lab-scott commented on api/src/main/kotlin/com/parking/api/adapter/out/ParkingLotInquiryAdapter.kt
> +class ParkingLotInquiryAdapter(
내가 등록한 주차장을 가져오는 Rest API가 보이던데요... 그 API에 대응되는 유즈 케이스가 있어야 할 것 같단 말씀이었습니다. @acecic82

2024-03-20 23:17 UTC, f-lab-scott commented on domain/src/main/kotlin/com/parking/domain/entity/ParkingLot.kt
> +        //5년 범위 안에 랜덤 값
네 어색하다고 생각합니다.
도메인에 위치시키실 거면 지울 수 있는 도메인 요소들이 공통적으로 채택할 수 있는 인터페이스를 정의하시는 것도 좋을 것 같습니다

```kotlin
interface DeletableObject {

    fun delete()
    fun isDeleted()
```

뭐 이런 식으로요 @acecic82

2024-03-20 23:55 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/out/ParkingLotInquiryAdapter.kt
> +class ParkingLotInquiryAdapter(
UseCase는 따로 있습니다. 

interface FindParkingLotUseCase {
    fun findAllByMemberId(currentUserName: String, memberId: String): List<ParkingLotListInfoVO>
}

이 usecase의 findAllByMemberId 에서 해당 adapter에 접근하여 가져옵니다.

parkingLotInquiryAdapter.findByMemberId(foundMemberId).map { ParkingLotListInfoVO.from(it) }

이런식으로 접근하여 가져옵니다.

Adapter 내의 Method 중에서 findByMemberId 말고 좀 더 내가 등록한 주차장을 가져오는것을 직관적으로 알 수 있는 메서드 명으로 바꿔야할것 같다는 말씀이신걸까요? @f-lab-scott

2024-03-20 23:56 UTC, acecic82 commented on domain/src/main/kotlin/com/parking/domain/entity/ParkingLot.kt
> +        //5년 범위 안에 랜덤 값
음... Repository 쪽으로 옮기도록 하겠습니다. 디비에서 만들어질 때만 필요한 값이기 때문에 만들어질 때만 사용하도록 하는게 더 나을것 같습니다.

2024-03-21 00:34 UTC, acecic82 commented on domain/src/main/kotlin/com/parking/domain/entity/ParkingLot.kt
> +        //5년 범위 안에 랜덤 값
수정 완료 했습니다

2024-03-21 00:35 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/in/ParkingLotCommandController.kt
> +    @DeleteMapping("/delete")
네 감사합니다.

2024-03-22 00:16 UTC, f-lab-scott commented on api/src/main/kotlin/com/parking/api/adapter/out/ParkingLotInquiryAdapter.kt
> +class ParkingLotInquiryAdapter(
아 네 이해했습니다. 아뇨 이것으로 충분한듯 싶습니다.

2024-03-22 00:17 UTC, f-lab-scott approved these changes

2024-03-22 03:00 UTC, merged