#14 NoShow 스케쥴러 추가
f-lab-edu/par-king pull request #18
Opened 2024-04-08 07:28 UTC by acecic82

1분 마다 체크하여 NoShow 상태로 바꿔야 하는 대상들을 찾아 NoShow 상태로 바뀌도록 개발

2024-04-20 00:49 UTC, f-lab-scott requested changes
간단한 것 두 가지 남겨봅니다.

2024-04-20 00:49 UTC, f-lab-scott commented on api/src/main/kotlin/com/parking/api/adapter/out/DibsOnParkingLotInquiryAdapter.kt
> +    override fun findDibsOnDataByOverTimeAndStatus(overTime: LocalDateTime, status: DibsOnParkingLotStatus): List<DibsOnParkingLot> {
Kotlin에서 이런 경우 함수 body를 쓰지 않고 `=` 기호로 치환하는 방법이 있을 것 같습니다. `return` 문도 필요 없고요.
요 표현법을 사용해보시는 것은 어떨지요?

https://www.jetbrains.com/guide/java/tips/convert-to-expression-body/

2024-04-20 00:49 UTC, f-lab-scott commented on api/src/main/kotlin/com/parking/api/application/schedule/NoShowSchedule.kt
> +        }
함수형 function이나 인터페이스들을 사용하실 때, 혹은 그런 스타일로 코딩하실 때 가급적이면 `.forEach{}` 는 사용 자제하시는 것이 좋습니다.

그리고 요 경우에는 `SaveNoShowUseCase` 에 `.saveAll()` 같은 함수가 구현되어 있는 것이 사용성에 좋을 것 같네요. `.saveAll()` 의 파라메터 타입은 어떤 것이 되어야 할까요? 한번 설계해 보시면 좋겠네요.

2024-04-21 01:40 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/adapter/out/DibsOnParkingLotInquiryAdapter.kt
> +    override fun findDibsOnDataByOverTimeAndStatus(overTime: LocalDateTime, status: DibsOnParkingLotStatus): List<DibsOnParkingLot> {
아 이거 dto에서는 자주 사용했었는데 여기도 그렇게 바꿔도 되겠네요 수정하겠습니다

2024-04-21 01:42 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/application/schedule/NoShowSchedule.kt
> +        }
그렇네요 parameter 만들어보겠습니다

2024-05-23 03:49 UTC, closed without merging