기본적 설정 추가
f-lab-edu/par-king pull request #2
Opened 2024-02-16 09:41 UTC by acecic82

1. JPA 설정 추가
2. QueryDSL 설정 추가
3. flyway 설정 추가
4. 간단한 member 조회 구현
5. par-king prefix 제거
6. 기본적 domain entity 추가

2024-02-17 07:12 UTC, f-lab-scott requested changes
일단 생각나는 대로 정리해 봤습니다

2024-02-17 07:12 UTC, f-lab-scott commented on domain/src/main/kotlin/domain/entity/NoShow.kt
> +    val parkingLotId: ParkingLot,
id인데 ParkingLot 엔티티를 그대로 받네요? 변수명이 좀 더 정교하면 좋겠습니다.

2024-02-17 07:12 UTC, f-lab-scott commented on domain/src/main/kotlin/domain/entity/ParkingLot.kt
> +data class ParkingLot(
변수들이 추가될 예정이겠지요? 지금은 좀 부족해 보여서요.

2024-02-17 07:12 UTC, f-lab-scott commented on domain/src/main/kotlin/domain/entity/ParkingLot.kt
> +    val guName: String
`ParkingLotAddress` 등의 밸류로 빼야 하지 않나 싶습니다. 구 만 있어야 할 건 아닌 것 같아서요~

2024-02-17 07:12 UTC, f-lab-scott commented on domain/src/main/kotlin/domain/entity/Password.kt
> +data class Password (
임의의 password challenge 값과 일치 여부를 알려주는 메소드도 있으면 좋을 것 같습니다.

2024-02-17 07:12 UTC, f-lab-scott commented on persistence/src/main/kotlin/jpa/configuration/DataSourceConfiguration.kt
> +        properties[AvailableSettings.USE_QUERY_CACHE] = false.toString()
그냥 "false" 라고 하면 될 것 같습니다.

2024-02-17 07:12 UTC, f-lab-scott commented on persistence/src/main/kotlin/jpa/entity/BaseEntity.kt
> +abstract class BaseEntity {
Gradle의 compiler plugin 이용해서 밑의 `open` 키워드 빼도 동작할 수 있는 방법 고민해 주세요.
https://plugins.gradle.org/plugin/org.jetbrains.kotlin.plugin.jpa

2024-02-17 07:12 UTC, f-lab-scott commented on persistence/src/main/kotlin/jpa/entity/BaseEntity.kt
> +abstract class BaseEntity {
이것도 참고 https://kotlinlang.org/docs/all-open-plugin.html

2024-02-17 07:12 UTC, f-lab-scott commented on persistence/src/main/kotlin/jpa/entity/MemberJpaEntity.kt
> +    val noShowCount: Long? = null,
0이면 되지 않나요? nullable해야 하는지 생각해봐주세요~

2024-02-17 08:57 UTC, acecic82 commented on domain/src/main/kotlin/domain/entity/NoShow.kt
> +    val parkingLotId: ParkingLot,
아 이 부분 Long으로 수정할 예정입니다. Id들은 Long으로 수정하겠습니다.

2024-02-17 08:57 UTC, acecic82 commented on domain/src/main/kotlin/domain/entity/ParkingLot.kt
> +data class ParkingLot(
네 아래에 있는 Info랑 category가 원래는 들어가야합니다. 추가하겠습니다

2024-02-17 08:58 UTC, acecic82 commented on domain/src/main/kotlin/domain/entity/ParkingLot.kt
> +    val guName: String
아 주소를 풀로 저장할 무언가가 필요할 수 있겠군요 말 그대로 카테고리별로 검색을 위해 만들어둔 값들이어서 address 를 추가하도록 하겠습니다. Full 주소도 있으면 좋겠네요

2024-02-17 08:59 UTC, acecic82 commented on domain/src/main/kotlin/domain/entity/Password.kt
> +data class Password (
이 부분은 spring security 하면서 같이 작업하려고 일단은 Entity만 추가해둔 상태입니다. spring security 적용하면서 넣어도 될까요?

2024-02-17 09:00 UTC, acecic82 commented on persistence/src/main/kotlin/jpa/configuration/DataSourceConfiguration.kt
> +        properties[AvailableSettings.USE_QUERY_CACHE] = false.toString()
수정하겠습니다

2024-02-17 09:02 UTC, acecic82 commented on persistence/src/main/kotlin/jpa/entity/MemberJpaEntity.kt
> +    val noShowCount: Long? = null,
0이어도 무관할것 같습니다. 널일필요는 없겠네요 수정하겠습니다

2024-02-17 10:02 UTC, acecic82 commented on persistence/src/main/kotlin/jpa/entity/BaseEntity.kt
> +abstract class BaseEntity {
확인해보겠습니다

2024-02-17 10:36 UTC, acecic82 commented on persistence/src/main/kotlin/jpa/entity/BaseEntity.kt
> +abstract class BaseEntity {
수정하였습니다.

2024-02-17 10:38 UTC, acecic82 commented on domain/src/main/kotlin/domain/entity/ParkingLot.kt
> +    val guName: String
parkingLotInfo에 fullAddress를 추가하는 형태로 수정하였습니다. 부족할까요?

2024-02-17 10:44 UTC, acecic82 commented on api/src/main/kotlin/api/ParkingApiApplication.kt
> +	System.setProperty("spring.config.name", "application-api, application-persistence")
시도해봤는데 유일하게 찾은 방법이라... 혹시 다른 방법이 있다면 알 수 있을까요?

2024-02-21 02:29 UTC, acecic82 commented on domain/src/main/kotlin/domain/entity/ParkingLot.kt
> +    val guName: String
category 대신 location으로 수정하였습니다

2024-02-22 06:05 UTC, f-lab-scott approved these changes

2024-02-22 06:50 UTC, merged