Spring security, jwt, redis 추가
f-lab-edu/par-king pull request #5
Opened 2024-03-06 23:33 UTC by acecic82

주요 변경 내용

1. Spring security 설정 추가 
2. JWT 설정 및 기능 추가
3. sign-in, sign-up 기능 추가
4. redis 설정 및 일부 기능 추가(get, set, getStringValues)
5. Password를 Member에 속하도록 변경

2024-03-08 06:39 UTC, f-lab-scott requested changes
수정 의견 드립니다~

2024-03-08 06:39 UTC, f-lab-scott commented on api/build.gradle.kts
> +    implementation("io.jsonwebtoken:jjwt-jackson:0.11.5")
요렇게 세가지나 다 필요하지 않을 거 같네요
https://jwt.io/libraries 참고하셔서 정리해보시죠

2024-03-08 06:39 UTC, f-lab-scott commented on api/src/main/kotlin/api/Api.kt
> +}
허허 요건 용도가 뭘까요;;

2024-03-08 06:39 UTC, f-lab-scott commented on api/src/main/kotlin/api/ParkingApiApplication.kt
> +	scanBasePackageClasses = [Api::class, Redis::class]
아 요런용도구나... 전 근데 패키지 이름으로 하는 걸 선호하긴 합니다

2024-03-08 06:39 UTC, f-lab-scott commented on api/src/main/kotlin/api/ParkingApiApplication.kt
> +	scanBasePackageClasses = [Api::class, Redis::class]
이 이유뿐이라면 굳이 인터페이스를 따로 작성할 이유가 있을까요?

2024-03-08 06:39 UTC, f-lab-scott commented on api/src/main/kotlin/api/adapter/in/dto/MemberInfoDTO.kt
> +    val password: String? = null,
요  DTO를 아마 좀 범용적으로 사용하고 싶으신 것 같아요. 그래서 pw 필드가 nullable이 된 것 같은데..
제 의견 드리자면 DTO는 범용성이 좀 떨어져도 괜찮습니다. 만약 비밀번호나 이메일을 비우고 유저 정보를 내려야 하는 니즈가 있다면, 그것에 맞는 DTO를 새로 작성해 주심이 어떠할까요?

2024-03-08 06:39 UTC, f-lab-scott commented on api/src/main/kotlin/api/application/port/in/MakeAccessToken.kt
> +interface MakeAccessToken {
좀 더 나은 네이밍이 필요합니다

2024-03-08 06:39 UTC, f-lab-scott commented on api/src/main/kotlin/api/util/PasswordUtil.kt
> +class PasswordUtil(
`Util` 을 만들겠단 말씀이 이런 말씀이셨군요. 그런데 지금 아래 작성된 메서드가 `PasswordEncoder` 에 있는 것과 차이가 없어서요..
`PasswordEncoder` 를 필요하신 곳에 다 주입받아 사용하시면 될거같습니다.
요건 어떤 레이어든지간에 침투해도 되는 녀석입니다(api 제외)

2024-03-08 06:39 UTC, f-lab-scott commented on api/src/main/kotlin/api/common/jwt/JwtAuthenticationFilter.kt
> +        val token = authorizationHeader.substring("Bearer ".length)
`"Bearer"` 문자열 상수로 추출해주세요

2024-03-08 06:39 UTC, f-lab-scott commented on api/src/main/kotlin/api/common/jwt/JwtAuthenticationFilter.kt
> +    companion object {
저라면 요런 용도로 `companion object` 는 사용 안할 거 같습니다.
그냥 클래스바디 바깥 상단에 선언하고 글로벌 변수화 할거같아요

2024-03-08 06:39 UTC, f-lab-scott commented on api/src/main/kotlin/api/common/jwt/JwtAuthenticationFilter.kt
> +            logger.info("토큰 검증 성공")
토큰 검증 성공을.... 인포로그를 남겨야 할까요. ㅠㅠ

2024-03-08 06:39 UTC, f-lab-scott commented on api/src/main/kotlin/api/common/jwt/JwtAuthenticationFilter.kt
> +            logger.info("로그인 실패")
요것도 로그 레벨 재검토 부탁드려요.

2024-03-08 06:39 UTC, f-lab-scott commented on api/src/main/kotlin/api/common/jwt/JwtAuthenticationFilter.kt
> +            response.addCookie(Cookie("refresh", "true"))
슬랙으로 대화 나눈 내용인 거 같습니다.

2024-03-08 14:29 UTC, acecic82 commented on api/src/main/kotlin/api/adapter/in/dto/MemberInfoDTO.kt
> +    val password: String? = null,
이해 했습니다 분리하겠습니다

2024-03-08 14:29 UTC, acecic82 commented on api/src/main/kotlin/api/common/jwt/JwtAuthenticationFilter.kt
> +        val token = authorizationHeader.substring("Bearer ".length)
아이고 이걸 놓쳤네요 추출하겠습니다

2024-03-08 14:56 UTC, acecic82 commented on api/src/main/kotlin/api/common/jwt/JwtAuthenticationFilter.kt
> +    companion object {
음... 동의합니다. 다른 곳에서 사용하지 않기 때문에(이 클래스에서만 사용해서) 이렇게 의견주신거라 생각하는데 맞을까요? 우선 수정하겠습니다

2024-03-08 14:57 UTC, acecic82 commented on api/src/main/kotlin/api/common/jwt/JwtAuthenticationFilter.kt
> +            logger.info("토큰 검증 성공")
아니요 삭제하겠습니다.

2024-03-08 14:58 UTC, acecic82 commented on api/src/main/kotlin/api/common/jwt/JwtAuthenticationFilter.kt
> +            logger.info("로그인 실패")
warning이 적합해 보여서 변경하겠습니다

2024-03-08 16:00 UTC, f-lab-scott commented on api/src/main/kotlin/api/common/jwt/JwtAuthenticationFilter.kt
> +            logger.info("로그인 실패")
유저 개개인의 로그인 실패건인지라 로그 자체가 남지 않는 것이 더 좋아 보이는데, WARN으로 생각하신 이유가 있으실지요?

2024-03-08 17:09 UTC, acecic82 commented on api/src/main/kotlin/api/common/jwt/JwtAuthenticationFilter.kt
> +            logger.info("로그인 실패")
access token 만료되는 정도를 보고 시간을 좀 조정하기 위해 우선 warning으로 두고 적절한 시간을 찾으면 제거하는게 좋을것 같다고 생각했습니다. 너무 빈번하다 싶으면 시간을 늘려보는 방안도 검토한다던가(보안적 문제가 안되는 범위내에서) 일단 그렇게 생각했습니다. 근데 말씀하신대로 제거해도 문제는 없을것 같습니다

2024-03-11 10:46 UTC, f-lab-scott approved these changes

2024-03-11 15:10 UTC, merged