멤버 비지니스 로직 추가 및 Exception 처리 추가
f-lab-edu/par-king pull request #9
Opened 2024-03-14 20:16 UTC by acecic82

1. Advice를 이용하여 BusinessException 종류로 들어온 Exception들을 200번으로 처리할 수 있도록 추가
2. 로그인 시 패스워드가 맞을 경우 이전에 실패한 기록 삭제하는 기능 추가
3. 멤버 정보 수정 추가
4. 멤버 탈퇴 기능 추가

2024-03-15 15:20 UTC, f-lab-scott requested changes
하나만 봐주시면 좋겠습니다

2024-03-15 15:20 UTC, f-lab-scott commented on api/src/main/kotlin/com/parking/api/application/service/MemberCommandService.kt
> +        return true
요런 유즈케이스가 나올거라면 `.saveMember()` 의 리턴타입이 bool이여야 할 것 같습니다
실제 로직상에서 수행이 완료되었는지 알려줄 수 있게끔요.

물론... 실패하면 예외가 터지겠지만서도, 무작정 하드코딩된 true를 던지는 건 좋은 구현은 아닌 듯합니다

2024-03-16 11:42 UTC, f-lab-scott commented on api/src/main/kotlin/com/parking/api/application/service/MemberCommandService.kt
> +        return true
아니면 이 메소드의 리턴타입이 void인 것도 좋습니다.

2024-03-16 11:42 UTC, f-lab-scott commented on api/src/main/kotlin/com/parking/api/application/service/MemberCommandService.kt
> +        return true
일부러 확인까지 하는건 어색해서요 @acecic82

2024-03-16 11:46 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/application/service/MemberCommandService.kt
> +        return true
return type을 void로 하는것으로 진행하겠습니다. @f-lab-scott

2024-03-16 12:07 UTC, acecic82 commented on api/src/main/kotlin/com/parking/api/application/service/MemberCommandService.kt
> +        return true
수정 완료 하였습니다

2024-03-17 02:59 UTC, f-lab-scott approved these changes

2024-03-17 03:04 UTC, merged